// ── Service Checklist Task Definitions ───────────────────────────────────────
// Based on Alta Vision Solar Off-Grid / Hybrid / On-Grid Service Guide
// All tasks trilingual: English / සිංහල / தமிழ்

// Aligned with global SystemType in src/types/index.ts
export type SystemType =
  | "ongrid"        // On-Grid (Solar + Grid, no battery)
  | "hybrid"        // Hybrid (Solar + Grid + Battery)
  | "hybrid-offgrid"// Hybrid (Solar + Battery – No Grid)
  | "offgrid"       // Off-Grid (Solar + Battery, standalone)
  | "grid-backup";  // Grid Backup (Grid + Battery – No Solar)
export type ServiceScope = "full" | "panel" | "inverter" | "troubleshoot" | "expansion" | "repair" | "other";
export type SiteCategory = "standard" | "boc" | "ground_mount";
export type TaskCategory =
  | "serial" | "shutdown"
  | "roof" | "outdoor" | "battery" | "main_panel"
  | "wifi_router" | "handover"
  | "troubleshooting" | "repair" | "expansion_checks";
export type PhotoPhase = "before" | "during" | "after" | "data" | "issue";

export interface ChecklistTask {
  id: string;
  category: TaskCategory;
  label: string;
  labelSi: string;
  labelTa: string;
  systemTypes: SystemType[];
  serviceScopes: ServiceScope[];
  siteCategories?: SiteCategory[];   // undefined = all sites
  requiresPhoto: boolean;
  photoPhases?: PhotoPhase[];
  photoCommentSuggestions?: string[];
  photoCommentSuggestionsSi?: string[];
  photoCommentSuggestionsTa?: string[];
  hasTextInput?: boolean;
  inputLabel?: string;
  inputPlaceholder?: string;
  inputType?: "text" | "number" | "textarea";
  isRequired?: boolean;
}

export const CHECKLIST_TASKS: ChecklistTask[] = [

  // ════════════════════════════════════════════
  // SERIAL NUMBERS
  // ════════════════════════════════════════════
  {
    id: "inverter_serial",
    category: "serial",
    label: "Inverter Serial Nos. — record from nameplate",
    labelSi: "ඉන්වර්ටරය ශ්‍රේණිය අංකය — නාම ෆලකයෙන් සටහන් කරන්න",
    labelTa: "இன்வெர்ட்டர் தொடர் எண் — பெயர் தகட்டிலிருந்து எழுதவும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["data"],
    photoCommentSuggestions: ["Serial number", "Inverter nameplate", "Model plate", "Serial tag"],
    photoCommentSuggestionsSi: ["ශ්‍රේණිය අංකය", "නාම ෆලකය", "ආදර්ශ ෆලකය"],
    photoCommentSuggestionsTa: ["தொடர் எண்", "பெயர் தகடு", "மாதிரி தகடு"],
    hasTextInput: true,
    inputLabel: "Inverter Serial No.",
    inputPlaceholder: "e.g. SN12345678",
    isRequired: true,
  },
  {
    id: "battery_serial",
    category: "serial",
    label: "Battery Serial Nos. — record from nameplate",
    labelSi: "බැටරිය ශ්‍රේණිය අංකය — නාම ෆලකයෙන් සටහන් කරන්න",
    labelTa: "பேட்டரி தொடர் எண் — பெயர் தகட்டிலிருந்து எழுதவும்",
    systemTypes: ["hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["data"],
    photoCommentSuggestions: ["Battery serial", "Battery nameplate", "BMS label", "Battery tag"],
    photoCommentSuggestionsSi: ["බැටරිය ශ්‍රේණිය", "නාම ෆලකය", "BMS ලේබලය"],
    photoCommentSuggestionsTa: ["பேட்டரி தொடர்", "பெயர் தகடு", "BMS லேபிள்"],
    hasTextInput: true,
    inputLabel: "Battery Serial No.",
    inputPlaceholder: "e.g. BAT-SN123456",
    isRequired: true,
  },
  // SEC serials are handled dynamically in SiteChecklist based on secUnitConfig
  // These marker tasks trigger the dynamic SEC serial section
  {
    id: "sec_serials",
    category: "serial",
    label: "SEC Unit Serial Nos. — photograph nameplate of each unit",
    labelSi: "SEC ඒකකය ශ්‍රේණිය අංක — සෑම ඒකකයකම නාම ෆලකය ඡායාරූප",
    labelTa: "SEC அலகு தொடர் எண்கள் — ஒவ்வொரு அலகிலும் பெயர் தகட்டின் புகைப்படம்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    siteCategories: ["boc", "ground_mount"],
    requiresPhoto: true,
    photoPhases: ["data"],
    photoCommentSuggestions: ["SEC unit 1 serial", "SEC unit 2 serial", "SEC nameplate", "SEC label"],
    photoCommentSuggestionsSi: ["SEC ඒකකය 1 ශ්‍රේණිය", "SEC ඒකකය 2 ශ්‍රේණිය", "SEC නාම ෆලකය"],
    photoCommentSuggestionsTa: ["SEC அலகு 1 எண்", "SEC அலகு 2 எண்", "SEC பெயர் தகடு"],
    hasTextInput: false,
    isRequired: true,
  },

  // ════════════════════════════════════════════
  // SHUTDOWN (Step 5 of guide)
  // ════════════════════════════════════════════
  {
    id: "switch_off_ac",
    category: "shutdown",
    label: "Switch OFF AC side of Panel Box",
    labelSi: "Panel Box-හි AC පැත්ත ස්විච් ඕෆ් කරන්න",
    labelTa: "Panel Box-இன் AC பக்கத்தை அணைக்கவும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "panel", "inverter"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "switch_off_dc",
    category: "shutdown",
    label: "Switch OFF DC side of Panel Box",
    labelSi: "Panel Box-හි DC පැත්ත ස්විච් ඕෆ් කරන්න",
    labelTa: "Panel Box-இன் DC பக்கத்தை அணைக்கவும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "panel", "inverter"],
    requiresPhoto: false,
    isRequired: true,
  },

  // ════════════════════════════════════════════
  // ROOF WORK
  // ════════════════════════════════════════════
  {
    id: "cloudiness",
    category: "roof",
    label: "Cloudiness (1–10) — record sky condition at time of service",
    labelSi: "වළාකුළු (1–10) — සේවාව කරන විට අහස් තත්ත්වය",
    labelTa: "மேகமூட்டம் (1–10) — சேவை நேரத்தில் வானிலை",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["full", "panel"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Cloudiness (1–10)",
    inputPlaceholder: "e.g. 3",
    inputType: "number",
    isRequired: true,
  },
  {
    id: "panel_service",
    category: "roof",
    label: "Panel Service — washed and inspected",
    labelSi: "පැනල් සේවාව — සේදා පරීක්ෂා කිරීම",
    labelTa: "பேனல் சேவை — கழுவி ஆய்வு செய்யவும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["full", "panel"],
    requiresPhoto: true,
    photoPhases: ["before", "after"],
    photoCommentSuggestions: ["Before cleaning", "After cleaning", "Heavy dust", "Clean panels", "Bird droppings", "All rows done"],
    photoCommentSuggestionsSi: ["පිරිසිදු කිරීමට පෙර", "පිරිසිදු කිරීමෙන් පසු", "දූවිලි", "පිරිසිදු"],
    photoCommentSuggestionsTa: ["சுத்தம் முன்", "சுத்தம் பின்", "தூசு", "சுத்தமான பேனல்"],
    isRequired: true,
  },
  {
    id: "structure_service",
    category: "roof",
    label: "Structure Service — mounting, racking checked",
    labelSi: "ව්‍යුහ සේවාව — Mounting, Racking පරීක්ෂා",
    labelTa: "கட்டமைப்பு சேவை — நிறுவல், ரேக்கிங் சரிபார்ப்பு",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["full", "panel"],
    requiresPhoto: true,
    photoPhases: ["issue"],
    photoCommentSuggestions: ["Mounting good", "Rack loose", "Corrosion found", "Structure ok", "Bracket check"],
    photoCommentSuggestionsSi: ["Mounting හොඳ", "Rack ලිහිල්", "Corrosion", "හොඳ"],
    photoCommentSuggestionsTa: ["நிறுவல் நல்லது", "ரேக் தளர்வு", "துரு", "நல்ல நிலை"],
  },
  {
    id: "nuts_bolts",
    category: "roof",
    label: "Condition and tightness of Nut/Bolts checked",
    labelSi: "Nut/Bolt-හි තත්ත්වය සහ ශ්‍රාවිතකම පරීක්ෂා",
    labelTa: "நட்/போல்ட் நிலை மற்றும் இறுக்கம் சரிபார்க்கவும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["full", "panel"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "shadow_check",
    category: "roof",
    label: "Shadow — check for shading on panels",
    labelSi: "සෙවන — පැනල් මත සෙවන ඇති දැයි පරීක්ෂා",
    labelTa: "நிழல் — பேனல்கள் மீது நிழல் இருக்கிறதா என சரிபார்க்கவும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["full", "panel"],
    requiresPhoto: true,
    photoPhases: ["issue"],
    photoCommentSuggestions: ["Shadow found", "Tree shadow", "No shadow", "Partial shading", "Shadow clear"],
    photoCommentSuggestionsSi: ["සෙවන ඇත", "ගස් සෙවන", "සෙවන නොමැත", "අර්ධ සෙවන"],
    photoCommentSuggestionsTa: ["நிழல் உள்ளது", "மர நிழல்", "நிழல் இல்லை", "பகுதி நிழல்"],
  },
  {
    id: "panel_mc4",
    category: "roof",
    label: "Panel MC4 Condition — check connectors for damage or looseness",
    labelSi: "Panel MC4 කොන්ඩිශන් — ප්ලගිස් හානිය හෝ ලිහිල් ඇතිදැයි",
    labelTa: "Panel MC4 நிலை — இணைப்பிகளில் சேதம் அல்லது தளர்வு உள்ளதா",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["full", "panel"],
    requiresPhoto: true,
    photoPhases: ["issue"],
    photoCommentSuggestions: ["MC4 good", "MC4 loose", "MC4 damaged", "Connector ok", "Burn marks"],
    photoCommentSuggestionsSi: ["MC4 හොඳ", "MC4 ලිහිල්", "MC4 හානිය", "ගිනිදාහ"],
    photoCommentSuggestionsTa: ["MC4 நல்லது", "MC4 தளர்வு", "MC4 சேதம்", "எரிவு"],
    isRequired: true,
  },
  {
    id: "roof_photos",
    category: "roof",
    label: "Roof photos taken — before, after, any issues",
    labelSi: "වහල ඡායාරූප ගන්නා ලදි — ඊට පෙර, පසු, ගැටළු",
    labelTa: "கூரை புகைப்படங்கள் எடுக்கப்பட்டன — முன், பின், சிக்கல்கள்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["full", "panel"],
    requiresPhoto: true,
    photoPhases: ["before", "during", "after"],
    photoCommentSuggestions: ["Before work", "During work", "After work", "Full array", "Row 1", "Row 2", "Roof clean"],
    photoCommentSuggestionsSi: ["වැඩට පෙර", "වැඩ ගමන්", "වැඩ පසු", "සම්පූර්ණ ශ්‍රේණිය"],
    photoCommentSuggestionsTa: ["வேலைக்கு முன்", "வேலை நடவடிக்கை", "வேலைக்கு பின்", "முழு வரிசை"],
    isRequired: true,
  },

  // ════════════════════════════════════════════
  // OUTDOOR WORK
  // ════════════════════════════════════════════
  {
    id: "ceb_export",
    category: "outdoor",
    label: "CEB Export Reading — meter reading (kWh)",
    labelSi: "CEB Export කියවීම — මීටර් කියවීම (kWh)",
    labelTa: "CEB ஏற்றுமதி வாசிப்பு — மீட்டர் வாசிப்பு (kWh)",
    systemTypes: ["ongrid", "hybrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["data"],
    photoCommentSuggestions: ["Export meter", "CEB export", "kWh reading", "Meter photo", "Export reading"],
    photoCommentSuggestionsSi: ["Export මීටරය", "CEB export", "kWh"],
    photoCommentSuggestionsTa: ["ஏற்றுமதி மீட்டர்", "CEB ஏற்றுமதி", "kWh"],
    hasTextInput: true,
    inputLabel: "CEB Export (kWh)",
    inputPlaceholder: "e.g. 12345.6",
  },
  {
    id: "ceb_import",
    category: "outdoor",
    label: "CEB Import Reading — meter reading (kWh)",
    labelSi: "CEB Import කියවීම — මීටර් කියවීම (kWh)",
    labelTa: "CEB இறக்குமதி வாசிப்பு — மீட்டர் வாசிப்பு (kWh)",
    systemTypes: ["ongrid", "hybrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["data"],
    photoCommentSuggestions: ["Import meter", "CEB import", "kWh reading", "Meter photo"],
    photoCommentSuggestionsSi: ["Import මීටරය", "CEB import", "kWh"],
    photoCommentSuggestionsTa: ["இறக்குமதி மீட்டர்", "CEB இறக்குமதி", "kWh"],
    hasTextInput: true,
    inputLabel: "CEB Import (kWh)",
    inputPlaceholder: "e.g. 5678.9",
  },
  {
    id: "ground_resistance",
    category: "outdoor",
    label: "Ground Resistance — measure and record (Ω)",
    labelSi: "ග‍්‍රවුන්ඩ් ප්‍රතිරෝධය — මැනීම සහ සටහන් (Ω)",
    labelTa: "நில மின்தடை — அளவிடுதல் மற்றும் பதிவு (Ω)",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Ground Resistance (Ω)",
    inputPlaceholder: "e.g. 0.5",
  },
  {
    id: "earthing_rod",
    category: "outdoor",
    label: "Earthing Rod Connection Checked",
    labelSi: "Earthing Rod සම්බන්ධකය පරීක්ෂා කිරීම",
    labelTa: "Earthing Rod இணைப்பு சரிபார்க்கவும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    isRequired: true,
  },

  // ════════════════════════════════════════════
  // BATTERY (hybrid / offgrid / grid-backup)
  // ════════════════════════════════════════════
  {
    id: "bat_visual",
    category: "battery",
    label: "Battery Physical Inspection — check for swelling, leaks, damage",
    labelSi: "බැටරිය භෞතික පරීක්ෂාව — ගිනිදාහ, කාන්දු, හානිය",
    labelTa: "பேட்டரி உடல் சரிபார்ப்பு — வீக்கம், கசிவு, சேதம்",
    systemTypes: ["hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["issue"],
    photoCommentSuggestions: ["Battery swelling", "Battery leaks", "Battery damage", "Battery ok", "Enclosure check"],
    photoCommentSuggestionsSi: ["බැටරිය ගිනිදාහ", "කාන්දු", "හානිය", "බැටරිය හොඳ"],
    photoCommentSuggestionsTa: ["பேட்டரி வீக்கம்", "கசிவு", "சேதம்", "பேட்டரி நல்லது"],
    isRequired: true,
  },
  {
    id: "bat_clean",
    category: "battery",
    label: "Battery Unit Cleaned — dust and debris removed",
    labelSi: "බැටරිය ඒකකය පිරිසිදු — දූවිලි ඉවත් කිරීම",
    labelTa: "பேட்டரி அலகு சுத்தம் — தூசி நீக்கம்",
    systemTypes: ["hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["before", "after"],
    photoCommentSuggestions: ["Before clean", "After clean", "Battery enclosure", "Battery module"],
    photoCommentSuggestionsSi: ["පිරිසිදු කිරීමට පෙර", "පිරිසිදු කිරීමෙන් පසු", "Battery enclosure"],
    photoCommentSuggestionsTa: ["சுத்தம் முன்", "சுத்தம் பின்", "Battery enclosure"],
    isRequired: true,
  },
  {
    id: "bat_connections",
    category: "battery",
    label: "Battery Terminal Connections — no burn marks, tight, clean",
    labelSi: "බැටරිය ටර්මිනල් — ගිනිදාහ නොමැත, ශ්‍රාවිත, පිරිසිදු",
    labelTa: "பேட்டரி இணைப்புகள் — எரிவு இல்லை, இறுக்கமாக, சுத்தம்",
    systemTypes: ["hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["issue"],
    photoCommentSuggestions: ["Terminals ok", "Burn marks", "Loose connection", "Corrosion", "Terminal clean"],
    photoCommentSuggestionsSi: ["ටර්මිනල් හොඳ", "ගිනිදාහ", "ලිහිල්", "Corrosion"],
    photoCommentSuggestionsTa: ["இணைப்பு நல்லது", "எரிவு", "தளர்வு", "துரு"],
    isRequired: true,
  },
  {
    id: "bat_voltage",
    category: "battery",
    label: "Battery Bank Voltage — measured at terminals (V)",
    labelSi: "බැටරිය Bank Voltage — Terminals හිදී (V)",
    labelTa: "பேட்டரி வங்கி மின்னழுத்தம் — (V)",
    systemTypes: ["hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Battery Voltage (V)",
    inputPlaceholder: "e.g. 52.4",
  },
  {
    id: "bat_soc",
    category: "battery",
    label: "State of Charge (SOC) — from BMS or inverter display",
    labelSi: "State of Charge (SOC) — BMS හෝ ඩිස්ප්ලේ (%)",
    labelTa: "State of Charge (SOC) — BMS அல்லது காட்சி (%)",
    systemTypes: ["hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["data"],
    photoCommentSuggestions: ["SOC display", "BMS reading", "Battery SOC", "Charge level"],
    photoCommentSuggestionsSi: ["SOC ඩිස්ප්ලේ", "BMS කියවීම", "ෂාර්ජ් මට්ටම"],
    photoCommentSuggestionsTa: ["SOC காட்சி", "BMS வாசிப்பு", "சார்ஜ் நிலை"],
    hasTextInput: true,
    inputLabel: "SOC (%)",
    inputPlaceholder: "e.g. 85",
    isRequired: true,
  },
  {
    id: "bat_temperature",
    category: "battery",
    label: "Battery Temperature — within safe range (°C)",
    labelSi: "බැටරිය උෂ්ණත්වය — ආරක්ෂිත සීමාව (°C)",
    labelTa: "பேட்டரி வெப்பநிலை — பாதுகாப்பு வரம்பு (°C)",
    systemTypes: ["hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Temperature (°C)",
    inputPlaceholder: "e.g. 28",
  },
  {
    id: "bat_bms_errors",
    category: "battery",
    label: "BMS Status & Error Codes — check for alarms",
    labelSi: "BMS Status සහ Error Codes — අනතුරු ඇඟවීම්",
    labelTa: "BMS நிலை மற்றும் பிழை குறியீடுகள்",
    systemTypes: ["hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["data", "issue"],
    photoCommentSuggestions: ["BMS display", "Error code", "BMS normal", "BMS alarm", "Battery status"],
    photoCommentSuggestionsSi: ["BMS ඩිස්ප්ලේ", "Error code", "BMS සාමාන්‍ය", "BMS Alarm"],
    photoCommentSuggestionsTa: ["BMS காட்சி", "பிழை குறியீடு", "BMS சாதாரண", "BMS எச்சரிக்கை"],
    hasTextInput: true,
    inputLabel: "BMS Error Code (if any)",
    inputPlaceholder: "e.g. OVP, UVP, None",
    isRequired: true,
  },

  // ════════════════════════════════════════════
  // MAIN PANEL
  // ════════════════════════════════════════════
  {
    id: "online_grid_v",
    category: "main_panel",
    label: "Online Grid Voltage (V) — measure when inverter running",
    labelSi: "Online Grid Voltage (V) — ඉන්වර්ටරය ධාවනය වන විට",
    labelTa: "Online Grid Voltage (V) — இன்வெர்ட்டர் இயங்கும்போது அளவிடவும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Online Grid Voltage (V)",
    inputPlaceholder: "e.g. 230",
  },
  {
    id: "offline_grid_v",
    category: "main_panel",
    label: "Offline Grid Voltage (V) — measure without inverter",
    labelSi: "Offline Grid Voltage (V) — ඉන්වර්ටරය නොමැතිව",
    labelTa: "Offline Grid Voltage (V) — இன்வெர்ட்டர் இல்லாமல் அளவிடவும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Offline Grid Voltage (V)",
    inputPlaceholder: "e.g. 228",
  },
  {
    id: "inverter_service",
    category: "main_panel",
    label: "Inverter Service / Fan / Time — cleaned, fan checked, clock set",
    labelSi: "ඉන්වර්ටරය සේවාව / Fan / Time — පිරිසිදු, fan, ඔරලෝසු",
    labelTa: "இன்வெர்ட்டர் சேவை / Fan / Time — சுத்தம், விசிறி, நேரம்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["before", "after"],
    photoCommentSuggestions: ["Inverter before", "Inverter after", "Fan clean", "Inside dusty", "Display reading", "Inside clean"],
    photoCommentSuggestionsSi: ["ඉන්වර්ටරය ඊට පෙර", "ඉන්වර්ටරය පසු", "Fan පිරිසිදු"],
    photoCommentSuggestionsTa: ["முன் நிலை", "பின் நிலை", "விசிறி சுத்தம்"],
    isRequired: true,
  },
  {
    id: "breaker_service",
    category: "main_panel",
    label: "Breaker Service — clean and check all breakers",
    labelSi: "Breaker සේවාව — Breaker සියල්ල පිරිසිදු, පරීක්ෂා",
    labelTa: "Breaker சேவை — அனைத்து Breaker-ஐயும் சுத்தம் மற்றும் சரிபார்க்கவும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "dc_surge",
    category: "main_panel",
    label: "DC Surge Arrestors — checked and functional",
    labelSi: "DC Surge Arrestors — පරීක්ෂා, ක්‍රියාකාරී",
    labelTa: "DC Surge Arrestors — சரிபார்க்கப்பட்டு செயல்படுகிறது",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "ac_surge",
    category: "main_panel",
    label: "AC Surge Arrestors — checked and functional",
    labelSi: "AC Surge Arrestors — පරීක්ෂා, ක්‍රියාකාරී",
    labelTa: "AC Surge Arrestors — சரிபார்க்கப்பட்டு செயல்படுகிறது",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "mc4_inverter",
    category: "main_panel",
    label: "Inverter Connection (MC4) Condition — no burn marks, tight",
    labelSi: "ඉන්වර්ටරය MC4 කොන්ඩිශන් — ගිනිදාහ නොමැත, ශ්‍රාවිත",
    labelTa: "இன்வெர்ட்டர் MC4 நிலை — எரிவு இல்லை, இறுக்கமாக உள்ளது",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["issue"],
    photoCommentSuggestions: ["MC4 ok", "Burn marks", "MC4 loose", "Connection tight", "No issues"],
    photoCommentSuggestionsSi: ["MC4 හොඳ", "ගිනිදාහ", "MC4 ලිහිල්", "ශ්‍රාවිත"],
    photoCommentSuggestionsTa: ["MC4 நல்லது", "எரிவு", "MC4 தளர்வு", "இறுக்கமாக"],
    isRequired: true,
  },
  {
    id: "low_voltage",
    category: "main_panel",
    label: "Low Voltage Range — inverter setting (V)",
    labelSi: "Low Voltage Range — ඉන්වර්ටරය සැකසුම (V)",
    labelTa: "Low Voltage Range — இன்வெர்ட்டர் அமைப்பு (V)",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Low Voltage Range (V)",
    inputPlaceholder: "e.g. 180",
  },
  {
    id: "high_voltage",
    category: "main_panel",
    label: "High Voltage Range — inverter setting (V)",
    labelSi: "High Voltage Range — ඉන්වර්ටරය සැකසුම (V)",
    labelTa: "High Voltage Range — இன்வெர்ட்டர் அமைப்பு (V)",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "High Voltage Range (V)",
    inputPlaceholder: "e.g. 270",
  },
  {
    id: "low_frequency",
    category: "main_panel",
    label: "Low Frequency Range — inverter setting (Hz)",
    labelSi: "Low Frequency Range — ඉන්වර්ටරය සැකසුම (Hz)",
    labelTa: "Low Frequency Range — இன்வெர்ட்டர் அமைப்பு (Hz)",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Low Frequency (Hz)",
    inputPlaceholder: "e.g. 47",
  },
  {
    id: "high_frequency",
    category: "main_panel",
    label: "High Frequency Range — inverter setting (Hz)",
    labelSi: "High Frequency Range — ඉන්වර්ටරය සැකසුම (Hz)",
    labelTa: "High Frequency Range — இன்வெர்ட்டர் அமைப்பு (Hz)",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "High Frequency (Hz)",
    inputPlaceholder: "e.g. 51",
  },
  {
    id: "startup_time",
    category: "main_panel",
    label: "Inverter Startup Time — record from inverter display",
    labelSi: "Inverter Startup Time — ඉන්වර්ටරය ඩිස්ප්ලේ කියවීම",
    labelTa: "Inverter Startup Time — இன்வெர்ட்டர் காட்சியிலிருந்து பதிவு",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Startup Time",
    inputPlaceholder: "e.g. 60 sec",
  },
  {
    id: "e_today",
    category: "main_panel",
    label: "E-Today Inverter — energy generated today (kWh)",
    labelSi: "E-Today Inverter — අද ජනනය (kWh)",
    labelTa: "E-Today Inverter — இன்று உற்பத்தி (kWh)",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["data"],
    photoCommentSuggestions: ["E-Today display", "Today generation", "kWh today", "Inverter display"],
    photoCommentSuggestionsSi: ["E-Today ඩිස්ප්ලේ", "අද ජනනය", "kWh"],
    photoCommentSuggestionsTa: ["E-Today காட்சி", "இன்று உற்பத்தி", "kWh"],
    hasTextInput: true,
    inputLabel: "E-Today (kWh)",
    inputPlaceholder: "e.g. 12.5",
  },
  {
    id: "e_total",
    category: "main_panel",
    label: "E-Total Inverter — cumulative energy generated (kWh)",
    labelSi: "E-Total Inverter — සම්පූර්ණ ජනනය (kWh)",
    labelTa: "E-Total Inverter — மொத்த உற்பத்தி (kWh)",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["data"],
    photoCommentSuggestions: ["E-Total display", "Total generation", "kWh total", "Lifetime kWh"],
    photoCommentSuggestionsSi: ["E-Total ඩිස්ප්ලේ", "සම්පූර්ණ ජනනය", "kWh"],
    photoCommentSuggestionsTa: ["E-Total காட்சி", "மொத்த உற்பத்தி", "kWh"],
    hasTextInput: true,
    inputLabel: "E-Total (kWh)",
    inputPlaceholder: "e.g. 15432.1",
  },
  {
    id: "main_panel_photos",
    category: "main_panel",
    label: "Took photos of Main Panel Board — before and after",
    labelSi: "Main Panel Board ඡායාරූප — ඊට පෙර සහ පසු",
    labelTa: "Main Panel Board புகைப்படங்கள் — முன் மற்றும் பின்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["before", "after"],
    photoCommentSuggestions: ["Panel board before", "Panel board after", "Main board", "Breaker panel", "Inside panel"],
    photoCommentSuggestionsSi: ["Panel board ඊට පෙර", "Panel board පසු", "Main board"],
    photoCommentSuggestionsTa: ["Panel board முன்", "Panel board பின்", "Main board"],
    isRequired: true,
  },

  // ════════════════════════════════════════════
  // WiFi & ROUTER CONFIGURATION
  // ════════════════════════════════════════════
  {
    id: "wifi_config",
    category: "wifi_router",
    label: "WiFi Config Done — monitoring connected to router",
    labelSi: "WiFi Config සම්පූර්ණ — Monitoring router සමඟ සම්බන්ධ",
    labelTa: "WiFi Config முடிந்தது — கண்காணிப்பு router-உடன் இணைக்கப்பட்டது",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "power_bulb",
    category: "wifi_router",
    label: "Power Bulb Blinking Style — Slow / Solid / Fast",
    labelSi: "Power Bulb Blink ස්‍ථිතිය — Slow / Solid / Fast",
    labelTa: "Power Bulb Blink நிலை — Slow / Solid / Fast",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Blinking Style",
    inputPlaceholder: "Slow / Solid / Fast",
  },
  {
    id: "router_username",
    category: "wifi_router",
    label: "Router Username",
    labelSi: "Router Username",
    labelTa: "Router Username",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Router Username",
    inputPlaceholder: "e.g. admin",
  },
  {
    id: "router_password",
    category: "wifi_router",
    label: "Router Password",
    labelSi: "Router Password",
    labelTa: "Router Password",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Router Password",
    inputPlaceholder: "e.g. admin123",
  },
  {
    id: "router_serial",
    category: "wifi_router",
    label: "Router Serial Number",
    labelSi: "Router ශ්‍රේණිය අංකය",
    labelTa: "Router தொடர் எண்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: false,
    hasTextInput: true,
    inputLabel: "Router Serial No.",
    inputPlaceholder: "e.g. RT-SN123456",
  },

  // ════════════════════════════════════════════
  // HANDOVER
  // ════════════════════════════════════════════
  {
    id: "av_sticker",
    category: "handover",
    label: "Service / Alta Vision Sticker placed",
    labelSi: "Service / Alta Vision Sticker ඇලවීම",
    labelTa: "Service / Alta Vision Sticker ஒட்டப்பட்டது",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "panel", "inverter"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "light_bill",
    category: "handover",
    label: "Capture Light Bill (Last 3 Months) — photograph or upload",
    labelSi: "Light Bill (අවසාන මාස 3) ඡායාරූප — ගන්නා ලදි",
    labelTa: "Light Bill (கடந்த 3 மாதங்கள்) புகைப்படம் — எடுக்கப்பட்டது",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["full", "inverter"],
    requiresPhoto: true,
    photoPhases: ["data"],
    photoCommentSuggestions: ["Light bill month 1", "Light bill month 2", "Light bill month 3", "CEB bill", "Bill photo"],
    photoCommentSuggestionsSi: ["Light bill 1", "Light bill 2", "Light bill 3", "CEB බිල"],
    photoCommentSuggestionsTa: ["Light bill 1", "Light bill 2", "Light bill 3", "CEB பில்"],
  },
  // ════════════════════════════════════════════
  // 7. TROUBLESHOOTING
  // ════════════════════════════════════════════
  {
    id: "ts_error_logs",
    category: "troubleshooting",
    label: "Record Inverter Error Logs / Fault Codes",
    labelSi: "ඉන්වර්ටරයේ දෝෂ කේත සටහන් කිරීම",
    labelTa: "இன்வெர்ட்டர் பிழை குறியீடுகள் பதிவு",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["troubleshoot"],
    requiresPhoto: true,
    photoPhases: ["issue", "after"],
    isRequired: true,
  },
  {
    id: "ts_ac_voltage",
    category: "troubleshooting",
    label: "Check AC Voltage & Grid Frequency",
    labelSi: "AC වෝල්ටීයතාවය සහ සංඛ්‍යාතය පරීක්ෂා කිරීම",
    labelTa: "AC மின்னழுத்தம் மற்றும் அதிர்வெண் சரிபார்ப்பு",
    systemTypes: ["ongrid", "hybrid", "grid-backup"],
    serviceScopes: ["troubleshoot"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "ts_dc_voltage",
    category: "troubleshooting",
    label: "Check DC Voltage & Insulation Resistance",
    labelSi: "DC වෝල්ටීයතාවය සහ පරිවාරක ප්‍රතිරෝධය පරීක්ෂා කිරීම",
    labelTa: "DC மின்னழுத்தம் மற்றும் காப்பு எதிர்ப்பு சரிபார்ப்பு",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["troubleshoot"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "ts_mc4_isolator",
    category: "troubleshooting",
    label: "Inspect MC4 Connectors & DC Isolator for burn marks",
    labelSi: "MC4 කනෙක්ටර් සහ DC අයිසොලේටරයේ පිළිස්සුම් ලක්ෂණ පරීක්ෂාව",
    labelTa: "MC4 இணைப்பிகள் மற்றும் DC ஐசோலேட்டரில் எரிகாயங்கள் சரிபார்ப்பு",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["troubleshoot"],
    requiresPhoto: true,
    photoPhases: ["issue"],
    isRequired: true,
  },
  {
    id: "ts_ac_breakers",
    category: "troubleshooting",
    label: "Inspect AC Breakers & Surge Arrestors",
    labelSi: "AC බ්‍රේකර් සහ සර්ජ් ඇරෙස්ටර් පරීක්ෂාව",
    labelTa: "AC பிரேக்கர்கள் மற்றும் சர்ஜ் அரெஸ்டர்கள் சரிபார்ப்பு",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["troubleshoot"],
    requiresPhoto: true,
    photoPhases: ["issue"],
    isRequired: true,
  },
  {
    id: "ts_actions_taken",
    category: "troubleshooting",
    label: "Record Actions Taken & Components Replaced",
    labelSi: "ගත් ක්‍රියාමාර්ග සහ මාරු කළ කොටස් සටහන් කිරීම",
    labelTa: "எடுக்கப்பட்ட நடவடிக்கைகள் மற்றும் மாற்றப்பட்ட பாகங்கள் பதிவு",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["troubleshoot"],
    requiresPhoto: true,
    photoPhases: ["after"],
    isRequired: true,
  },
  {
    id: "ts_what_found",
    category: "troubleshooting",
    label: "Root Cause / Fault Found — describe what was discovered",
    labelSi: "Root Cause / දෝෂය — සොයාගත් දේ විස්තර කරන්න",
    labelTa: "Root Cause / தவறு — கண்டுபிடித்தது விவரிக்கவும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["troubleshoot"],
    requiresPhoto: false,
    hasTextInput: true,
    inputType: "textarea",
    inputLabel: "What fault / issue was found",
    inputPlaceholder: "Describe the fault, root cause, and symptoms observed…",
    isRequired: true,
  },
  {
    id: "ts_what_done",
    category: "troubleshooting",
    label: "Actions Taken — what was done to resolve the issue",
    labelSi: "ගත් ක්‍රියාමාර්ග — ගැටළුව විසඳීමට කළ දේ",
    labelTa: "எடுக்கப்பட்ட நடவடிக்கைகள் — சிக்கலை தீர்க்க செய்தது",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["troubleshoot"],
    requiresPhoto: false,
    hasTextInput: true,
    inputType: "textarea",
    inputLabel: "What was done to fix it",
    inputPlaceholder: "Describe the steps taken, parts adjusted, settings changed…",
    isRequired: true,
  },
  {
    id: "ts_items_takeaway",
    category: "troubleshooting",
    label: "Items Taken Back to Office — components or parts removed",
    labelSi: "කාර්යාලයට ගෙන ගිය දේ — ඉවත් කළ කොටස් ලැයිස්තුව",
    labelTa: "அலுவலகத்திற்கு எடுத்தவை — நீக்கப்பட்ட பாகங்கள்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["troubleshoot"],
    requiresPhoto: true,
    photoPhases: ["issue"],
    photoCommentSuggestions: ["Item removed", "Faulty component", "Parts for repair", "Warranty return"],
    photoCommentSuggestionsSi: ["ඉවත් කළ දේ", "දෝෂ සහිත", "අළුත්වැඩියා සඳහා"],
    photoCommentSuggestionsTa: ["நீக்கப்பட்டது", "பழுதான பாகம்", "பழுது சரி"],
    hasTextInput: true,
    inputType: "textarea",
    inputLabel: "Items taken back (one per line, or 'None')",
    inputPlaceholder: "e.g.\nFailed inverter fan (SN: XYZ)\nBurnt MC4 connector\nNone",
  },

  // ════════════════════════════════════════════
  // REPAIR
  // ════════════════════════════════════════════
  {
    id: "rep_what_repaired",
    category: "repair",
    label: "What was Repaired / Replaced — component and work done",
    labelSi: "අළුත්වැඩියා / ප්‍රතිස්ථාපිත — කොම්පොනන්ටය සහ කාර්ය",
    labelTa: "பழுது பார்த்தது / மாற்றியது — பாகம் மற்றும் வேலை விவரம்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["repair"],
    requiresPhoto: false,
    hasTextInput: true,
    inputType: "textarea",
    inputLabel: "What was repaired or replaced",
    inputPlaceholder: "e.g.\nReplaced failed inverter fan\nRe-crimped MC4 connectors on String 2\nReplaced burnt AC breaker",
    isRequired: true,
  },
  {
    id: "rep_before_photos",
    category: "repair",
    label: "Before Repair Photos — photos of fault/component before repair",
    labelSi: "අළුත්වැඩියාවට පෙර ඡායාරූප",
    labelTa: "பழுது முன் புகைப்படங்கள்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["repair"],
    requiresPhoto: true,
    photoPhases: ["before", "issue"],
    photoCommentSuggestions: ["Fault location", "Damaged component", "Before repair", "Burn marks", "Component removed", "Failed part"],
    photoCommentSuggestionsSi: ["දෝෂ ස්ථානය", "හානිය", "ඊට පෙර", "ගිනිදාහ"],
    photoCommentSuggestionsTa: ["தவறு இடம்", "சேதம்", "முன் நிலை", "எரிவு"],
    isRequired: true,
  },
  {
    id: "rep_after_photos",
    category: "repair",
    label: "After Repair Photos — photos showing completed repair",
    labelSi: "අළුත්වැඩියාවෙන් පසු ඡායාරූප",
    labelTa: "பழுது பின் புகைப்படங்கள்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["repair"],
    requiresPhoto: true,
    photoPhases: ["after"],
    photoCommentSuggestions: ["After repair", "New component", "Repaired connection", "System running", "Fixed", "Replacement done"],
    photoCommentSuggestionsSi: ["පසු", "නව කොටස", "අළුත් සම්බන්ධතාව", "පද්ධතිය ක්‍රියාත්මක"],
    photoCommentSuggestionsTa: ["பழுது பின்", "புதிய பாகம்", "சரி செய்யப்பட்டது", "செயல்படுகிறது"],
    isRequired: true,
  },
  {
    id: "rep_items_takeaway",
    category: "repair",
    label: "Items Taken Back to Office — parts removed for disposal or warranty",
    labelSi: "කාර්යාලයට ගෙන ගිය දේ — ඉවත් කළ කොටස්",
    labelTa: "அலுவலகத்திற்கு எடுத்தவை — நீக்கப்பட்ட பாகங்கள்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["repair"],
    requiresPhoto: true,
    photoPhases: ["issue"],
    photoCommentSuggestions: ["Item removed", "Faulty part", "Warranty return", "Defective component"],
    photoCommentSuggestionsSi: ["ඉවත් කළ දේ", "Warranty සඳහා", "දෝෂ සහිත"],
    photoCommentSuggestionsTa: ["நீக்கப்பட்டது", "உத்தரவாத திரும்பல்", "பழுதான பாகம்"],
    hasTextInput: true,
    inputType: "textarea",
    inputLabel: "Items taken back (one per line, or 'None')",
    inputPlaceholder: "e.g.\nFailed capacitor (Board No. 3)\nBurnt MC4 pair\nFaulty BMS module\nNone",
  },

  // ════════════════════════════════════════════
  // 8. EXPANSION CHECKS
  // ════════════════════════════════════════════
  {
    id: "exp_what_expanded",
    category: "expansion_checks",
    label: "What was Expanded — describe new components added",
    labelSi: "පුළුල් කළ දේ — අලුත් කොම්පොනන්ට් විස්තරය",
    labelTa: "விரிவாக்கியது — புதிய பாகங்கள் விவரம்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["expansion"],
    requiresPhoto: false,
    hasTextInput: true,
    inputType: "textarea",
    inputLabel: "What was expanded / added",
    inputPlaceholder: "e.g.\n4 × 415W panels added to String 2\nInverter upgraded to 10kW Growatt\n2 × 100Ah batteries added",
    isRequired: true,
  },
  {
    id: "exp_inv_capacity",
    category: "expansion_checks",
    label: "Check Existing Inverter Max Capacity limits",
    labelSi: "දැනට ඇති ඉන්වර්ටරයේ උපරිම ධාරිතාවය පරීක්ෂාව",
    labelTa: "தற்போதைய இன்வெர்ட்டர் அதிகபட்ச திறன் சரிபார்ப்பு",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["expansion"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "exp_roof_structure",
    category: "expansion_checks",
    label: "Inspect existing roof structure for new panels",
    labelSi: "නව පැනල සඳහා වහලයේ ව්‍යුහය පරීක්ෂාව",
    labelTa: "புதிய பேனல்களுக்கான கூரை அமைப்பு சரிபார்ப்பு",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["expansion"],
    requiresPhoto: true,
    photoPhases: ["before"],
    isRequired: true,
  },
  {
    id: "exp_string_config",
    category: "expansion_checks",
    label: "Record new string configurations (Voltage/Current)",
    labelSi: "නව ස්ට්‍රිං සැකසුම් (වෝල්ටීයතාවය/ධාරාව) සටහන් කිරීම",
    labelTa: "புதிய சரம் உள்ளமைவுகள் (மின்னழுத்தம்/மின்னோட்டம்) பதிவு",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["expansion"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "exp_wire_sizing",
    category: "expansion_checks",
    label: "Verify wire sizing for increased capacity",
    labelSi: "වැඩි කළ ධාරිතාව සඳහා වයර් ප්‍රමාණය තහවුරු කිරීම",
    labelTa: "அதிகரித்த திறனுக்கான கம்பி அளவை சரிபார்த்தல்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"],
    serviceScopes: ["expansion"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "exp_wifi_update",
    category: "expansion_checks",
    label: "Update WiFi/Router monitoring with new capacity",
    labelSi: "නව ධාරිතාව සමග WiFi/Router අධීක්ෂණය යාවත්කාලීන කිරීම",
    labelTa: "புதிய திறனுடன் WiFi/Router கண்காணிப்பை மேம்படுத்துதல்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["expansion"],
    requiresPhoto: false,
    isRequired: true,
  },
  {
    id: "exp_new_serials",
    category: "expansion_checks",
    label: "New Component Serial Numbers — record all new item SNs",
    labelSi: "නව කොම්පොනන්ට් ශ්‍රේණිය අංක — සියලු නව SNs",
    labelTa: "புதிய பாகங்கள் தொடர் எண்கள் — அனைத்தும்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["expansion"],
    requiresPhoto: true,
    photoPhases: ["data"],
    photoCommentSuggestions: ["New panel SN", "New inverter SN", "New battery SN", "SN label", "Nameplate photo"],
    photoCommentSuggestionsSi: ["නව පැනල SN", "නව ඉන්වර්ටර SN", "නව බැටරිය SN"],
    photoCommentSuggestionsTa: ["புதிய பேனல் SN", "புதிய இன்வெர்ட்டர் SN", "புதிய பேட்டரி SN"],
    hasTextInput: true,
    inputType: "textarea",
    inputLabel: "Serial numbers (one per line)",
    inputPlaceholder: "e.g.\nPanel 1: SN-A12345\nPanel 2: SN-A12346\nBattery: BAT-789\nInverter: INV-XYZ",
    isRequired: true,
  },
  {
    id: "exp_new_items_photos",
    category: "expansion_checks",
    label: "New Items Installation Photos — before, during and after",
    labelSi: "නව ස්ථාපන ඡායාරූප — ස්ථාපනයට පෙර, ගමනේ සහ පසු",
    labelTa: "புதிய நிறுவல் புகைப்படங்கள் — முன், நடவடிக்கை, பின்",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["expansion"],
    requiresPhoto: true,
    photoPhases: ["before", "during", "after"],
    photoCommentSuggestions: ["Before installation", "During installation", "After installation", "New panels", "New inverter", "New battery", "Wiring done"],
    photoCommentSuggestionsSi: ["ස්ථාපනයට පෙර", "ස්ථාපනය ගමනේ", "ස්ථාපනෙන් පසු", "නව පැනල"],
    photoCommentSuggestionsTa: ["நிறுவல் முன்", "நிறுவல் நடவடிக்கை", "நிறுவல் பின்", "புதிய பேனல்"],
    isRequired: true,
  },
  {
    id: "exp_verify_new",
    category: "expansion_checks",
    label: "New Items Verified Working — test and confirm operation",
    labelSi: "නව ස්ථාපන සත්‍යාපනය — ක්‍රියාකාරීත්වය",
    labelTa: "புதிய நிறுவல் சரிபார்ப்பு — செயல்பாடு",
    systemTypes: ["ongrid", "hybrid", "hybrid-offgrid", "offgrid", "grid-backup"],
    serviceScopes: ["expansion"],
    requiresPhoto: true,
    photoPhases: ["after", "data"],
    photoCommentSuggestions: ["System running", "New capacity", "Inverter display", "E-Today after expansion", "Monitoring updated", "All strings OK"],
    photoCommentSuggestionsSi: ["පද්ධතිය ක්‍රියාත්මක", "නව ධාරිතාව", "ඉන්වර්ටරය ඩිස්ප්ලේ"],
    photoCommentSuggestionsTa: ["கணினி இயங்குகிறது", "புதிய திறன்", "இன்வெர்ட்டர் காட்சி"],
    isRequired: true,
  },
];

// ── Filter tasks for a specific site configuration ──
// repair → diagnostic (troubleshoot) tasks + repair-specific tasks
// other  → full service tasks
export const getTasksForSite = (sysType: SystemType, scope: ServiceScope, siteCat: SiteCategory) => {
  const matchScopes: ServiceScope[] =
    scope === "repair" ? ["troubleshoot", "repair"] :
    scope === "other"  ? ["full"] :
    [scope];
  return CHECKLIST_TASKS.filter(t => {
    if (!t.systemTypes.includes(sysType)) return false;
    if (!t.serviceScopes.some(s => matchScopes.includes(s))) return false;
    if (t.siteCategories && !t.siteCategories.includes(siteCat)) return false;
    return true;
  });
};

// ── Labels ──
export const TASK_CATEGORY_LABELS: Record<TaskCategory, { label: string; labelSi: string; labelTa: string; icon: string }> = {
  serial:           { label: "Serial Numbers",      labelSi: "ශ්‍රේණිය අංක",             labelTa: "தொடர் எண்கள்",                  icon: "🏷️" },
  shutdown:         { label: "System Shutdown",      labelSi: "පද්ධතිය අක්‍රිය",          labelTa: "கணினி அணைப்பு",                 icon: "⚡" },
  roof:             { label: "Roof Work",            labelSi: "වහල කාර්ය",               labelTa: "கூரை வேலை",                     icon: "☀️" },
  outdoor:          { label: "Outdoor Work",         labelSi: "බාහිර කාර්ය",             labelTa: "வெளிப்புற வேலை",                icon: "🌳" },
  battery:          { label: "Battery System",       labelSi: "බැටරිය පද්ධතිය",          labelTa: "பேட்டரி அமைப்பு",               icon: "🔋" },
  main_panel:       { label: "Main Panel",           labelSi: "Main Panel",               labelTa: "Main Panel",                     icon: "⚙️" },
  wifi_router:      { label: "WiFi & Router",        labelSi: "WiFi සහ Router",           labelTa: "WiFi மற்றும் Router",            icon: "📶" },
  handover:         { label: "Customer Handover",    labelSi: "පාරිභෝගික භාරදීම",       labelTa: "வாடிக்கையாளர் ஒப்படைப்பு",     icon: "🤝" },
  troubleshooting:  { label: "Troubleshooting",      labelSi: "දෝෂ සෙවීම",               labelTa: "பிழை நீக்கல்",                  icon: "🩺" },
  repair:           { label: "Repair",               labelSi: "අළුත්වැඩියාව",             labelTa: "பழுது பார்த்தல்",               icon: "🛠️" },
  expansion_checks: { label: "Expansion",            labelSi: "පද්ධති පුළුල් කිරීම",    labelTa: "விரிவாக்கம்",                    icon: "➕" },
};

export const PHOTO_PHASE_CONFIG: Record<PhotoPhase, { label: string; labelSi: string; labelTa: string; color: string; bg: string }> = {
  before: { label: "Before", labelSi: "ඊට පෙර", labelTa: "முன்", color: "text-amber-700", bg: "bg-amber-50 border-amber-200 dark:bg-amber-950/20 dark:border-amber-900/40" },
  during: { label: "During", labelSi: "ගමන් ගනිමින්", labelTa: "நடக்கும்போது", color: "text-blue-700", bg: "bg-blue-50 border-blue-200 dark:bg-blue-950/20 dark:border-blue-900/40" },
  after: { label: "After", labelSi: "ඉන් පසු", labelTa: "பிறகு", color: "text-emerald-700", bg: "bg-emerald-50 border-emerald-200 dark:bg-emerald-950/20 dark:border-emerald-900/40" },
  data: { label: "Data / Reading", labelSi: "දත්ත", labelTa: "தரவு", color: "text-purple-700", bg: "bg-purple-50 border-purple-200 dark:bg-purple-950/20 dark:border-purple-900/40" },
  issue: { label: "Issue / Defect", labelSi: "ගැටළු", labelTa: "சிக்கல்", color: "text-red-700", bg: "bg-red-50 border-red-200 dark:bg-red-950/20 dark:border-red-900/40" },
};

export const SYSTEM_TYPE_LABELS: Record<SystemType, { label: string; labelSi: string; labelTa: string; short: string }> = {
  "ongrid": { label: "On-Grid (Solar + Grid)", labelSi: "On-Grid", labelTa: "ஆன்-கிரிட்", short: "On-Grid" },
  "hybrid": { label: "Hybrid (Solar + Grid + Battery)", labelSi: "Hybrid", labelTa: "ஹைப்ரிட்", short: "Hybrid" },
  "hybrid-offgrid": { label: "Hybrid (Solar + Battery, No Grid)", labelSi: "Hybrid (Off-Grid)", labelTa: "ஹைப்ரிட் (ஆஃப்)", short: "Hybrid Off" },
  "offgrid": { label: "Off-Grid (Solar + Battery)", labelSi: "Off-Grid", labelTa: "ஆஃப்-கிரிட்", short: "Off-Grid" },
  "grid-backup": { label: "Grid Backup (Grid + Battery)", labelSi: "Grid Backup", labelTa: "கிரிட் பேக்கப்", short: "Grid Backup" },
};

export const SERVICE_SCOPE_LABELS: Record<ServiceScope, { label: string; labelSi: string; labelTa: string; desc: string }> = {
  full: { label: "Full Service", labelSi: "සම්පූර්ණ සේවාව", labelTa: "முழு சேவை", desc: "Panels + Inverter + Electrical" },
  panel: { label: "Panel Service Only", labelSi: "පැනල් සේවාව පමණි", labelTa: "பேனல் வேலை மட்டும்", desc: "Panel cleaning & inspection only" },
  inverter: { label: "Inverter Service Only", labelSi: "ඉන්වර්ටරය සේවාව පමණි", labelTa: "இன்வெர்ட்டர் வேலை", desc: "Inverter + Electrical (no panels)" },
  troubleshoot: { label: "Troubleshoot", labelSi: "දෝෂ සෙවීම", labelTa: "பிழை நீக்கல்", desc: "Fault-finding & diagnostic visit" },
  expansion: { label: "Expansion", labelSi: "පද්ධති පුළුල් කිරීම", labelTa: "விரிவாக்கம்", desc: "System capacity expansion / upgrade" },
  repair: { label: "Repair", labelSi: "අලුත්වැඩියාව", labelTa: "பழுது பார்த்தல்", desc: "Component repair / replacement" },
  other: { label: "Other", labelSi: "වෙනත්", labelTa: "மற்றவை", desc: "Other visit type" },
};

export const SITE_CATEGORY_LABELS: Record<SiteCategory, { label: string; labelSi: string; labelTa: string; desc: string }> = {
  standard: { label: "Standard", labelSi: "සාමාන්‍ය", labelTa: "சாதாரண", desc: "Residential / Commercial rooftop" },
  boc: { label: "BOC Site", labelSi: "BOC ස්ථාන", labelTa: "BOC தளம்", desc: "Has 1× SEC1000 unit" },
  ground_mount: { label: "Ground Mount", labelSi: "Ground Mount", labelTa: "நிலத்தில் நிறுவிய", desc: "Has 2× SEC3000 units" },
};

// ── DC String columns (fixed set, up to 8 strings) ──
export const DC_STRING_COUNT = 8;

// ── AC measurement points (fixed) ──
export const AC_POINTS = ["L1-N", "L2-N", "L3-N", "L1-L2", "L2-L3", "L1-L3", "N-E"] as const;
export type ACPoint = typeof AC_POINTS[number];

// ── SEC Unit configuration (per-site, set at plan creation) ──
export type SecUnitModel = "SEC1000" | "SEC3000";
export interface SecUnitConfig {
  count: number;          // 1 or 2 (default 2 for ground_mount, 1 for BOC)
  model: SecUnitModel;    // SEC1000 or SEC3000
}
export const DEFAULT_SEC_CONFIG: Record<SiteCategory, SecUnitConfig | null> = {
  standard: null,                                   // no SEC unit
  boc: { count: 1, model: "SEC1000" },         // 1× SEC1000
  ground_mount: { count: 2, model: "SEC3000" },         // 2× SEC3000 (default, configurable)
};

// ── Helper: systems that have batteries ──
export const SYSTEMS_WITH_BATTERY: SystemType[] = ["hybrid", "hybrid-offgrid", "offgrid", "grid-backup"];
// ── Helper: systems that have solar panels ──
export const SYSTEMS_WITH_PANELS: SystemType[] = ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"];
// ── Helper: systems connected to grid ──
export const SYSTEMS_WITH_GRID: SystemType[] = ["ongrid", "hybrid", "grid-backup"];
// ── Helper: systems with DC strings ──
export const SYSTEMS_WITH_DC_STRINGS: SystemType[] = ["ongrid", "hybrid", "hybrid-offgrid", "offgrid"];
